### ISSUE TITLE
Update Snowflake config with filter info

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/opendatadiscovery-integration-manifests#24]

**Comment by ValeriyWorld** [comment]
Seems like there is no fine way to implement list of strings in the template. So for now I have ended with just description about schemas_filter in Configure -> ODD Collector section with some examples and [link](https://blog.opendatadiscovery.org/filters-to-include-and-exclude-objects-from-ingest-9fceff77133a) to our post on Medium.
